@startuml
class IP_Scanner {
subnet_mask : String
start_ip : IP
end_ip : IP
scan_ip()
}

class Port_Scanner {
ports : int []
scan_flag : String
ip : IP
scan_ports()
os_detection()
service_detection()
}

class IP {
ip: String
}

class Network_Topology {
topology: Machine []
display_topology()
}

class Machine {
ip : IP
os : String
vulnerabilities: String []
}

IP_Scanner o-- IP
Port_Scanner o--IP
Machine o-- IP
Network_Topology o-- Machine
Machine o-- Vulnerabilities
Exploit o-- Machine
UI o-- Network_Topology
UI o-- IP_Scanner
UI o-- Port_Scanner

class Vulnerabilities {
identify_vulnerability()
add_vulnerability()
}

class Exploit {
machines: Machine []
exploit_list()
add_exploit()
delete_exploit()
find_exploit()
run_exploit()

}



class UI {
tabs : Widgets
topologies : Network_Topology []
ip_scanner : IP_Scanner
port_scanner : Port_Scanner
exploit : Exploit
show_vulnerabilities()
displays_topology()
run_scans()
save_to_file_pdf()
run_exploit()
}
@enduml


